### ISSUE TITLE
Doubts with this project

### ISSUE THREAD

**Issue by MordredFTC** [martonmiklos/ble_keyboard_fw#1]
Hi, I see your project on GitHub (the fork of DIY BLE keyboard) that you keep updating. My main doubts are:
1º- what is the specific code to upload to the MCU to communicate with the USB Host Shield?
2º- If I am not wrong, I need to wire the USB Host Shield with the MCU. Can I communicate with the pinout of your website?
3º- Where can I connect the battery?
4º- If I connect a hub of the adapter (putting the specific code for mouse), I can use keyboard and mouse simultaneously?

Thanks in advice, I want to create a usb to bluetooth adapter, but I am very confused because I want to use only the MCU, without an arduino. Its my first time using MCU.

**Comment by martonmiklos** [comment]
Hi @MordredFTC 

There might be some level of misunderstandig of this porject: no USB device is involved. For the hw details see: https://github.com/martonmiklos/ble_keyboard and https://hackaday.io/project/27133-samsung-np540u4e-to-ble-keyboard-conversion It is designed to be directly interfaced with a Samsung notebook's keyboard

**Comment by MordredFTC** [comment]
Ok, thanks and sorry. I suppose that you use the MCU with a USB host for the conversion.
